version: '3'


services: 
  backend:
    image: jcardenasmarquez/repoblemapp_backend
    ports:
      - "25000:25000"
    depends_on: 
      - mongo
    command: npm start
    networks: 
        - db-tier
        - frontendNetwork

  frontend:
    image: jcardenasmarquez/repoblemapp_frontend
    ports:
      - "4200:80"
    depends_on: 
      - backend
    networks: 
      - frontendNetwork
      
  mongo:
        image: mongo
        restart: always
        volumes:
          - mongo-data:/data/db
        networks:
          - db-tier



networks:
  frontendNetwork:

  db-tier:
    driver: bridge

volumes:
    mongo-data:
        driver: local